### ISSUE TITLE
Insufficient funds (0) to process payments (12.50078707); possibly waiting for txs.

### ISSUE THREAD

**Issue by TheBlackDrake** [z-classic/z-nomp#324]
I've seen this before in here, but couldn't get it to work.

Let me know what Info you need.

```
2018-04-14 16:19:32 [Pool]      [zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2018-04-14 16:19:32 [Pool]      [zclassic] (Thread 2) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2018-04-14 16:19:42 [Payments]  [zclassic] Insufficient funds (0) to process payments (12.50078707); possibly waiting for txs.
2018-04-14 16:19:42 [Payments]  [zclassic] Finished interval - time spent: 9ms total, 2ms redis, 4ms daemon RPC
2018-04-14 16:20:12 [Payments]  [zclassic] Insufficient funds (0) to process payments (12.50078707); possibly waiting for txs.
2018-04-14 16:20:12 [Payments]  [zclassic] Finished interval - time spent: 9ms total, 2ms redis, 5ms daemon RPC
2018-04-14 16:20:27 [Pool]      [zclassic] (Thread 1) No new blocks for 55 seconds - updating transactions & rebroadcasting work
2018-04-14 16:20:27 [Pool]      [zclassic] (Thread 2) No new blocks for 55 seconds - updating transactions & rebroadcasting work
```

```
./src/zcash-cli z_gettotalbalance
{
  "transparent": "0.00",
  "private": "12.50108707",
  "total": "12.50108707"
```

So seems to be in there, but can't get any payouts.

It's a private z-nomp server I have.
(2 threds 4GB RAM)

Don't see any other errors in the pool.

Also

![image](https://user-images.githubusercontent.com/10724791/38769269-361c0916-4000-11e8-997f-cab95fd585ff.png)

In my n-nomp Web interface

**Comment by christianreiss** [comment]
Smells like HUSH coin. Had the same issue; Fixed by:

- Transfering 1-2 HUSH Coins into the Mining Wallet and
- Setting the hush.json txee to the right amount.

After a while it started to work.

**Comment by TheBlackDrake** [comment]
Actually its zcl coin as you can see. But I will try to transfer some funds and see if it helps :)

**Comment by TheBlackDrake** [comment]
still have the first blockreward stuck. but all the others are coming through.
So I'm gonna just transfer the first block manually.

:)
